name: Expensy CI/CD Pipelines - IaC Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ============================================================
    # Checkout
    # ============================================================
    - name: Checkout code
      uses: actions/checkout@v4


    # ============================================================
    # Checkov Security Scan
    # ============================================================
    - name: Checkov - Terraform scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform/
        framework: terraform
        output_format: sarif       # Generiert das SARIF-Format
        output_file_path: results.sarif
        soft_fail: true
        # Ignoriert alle Regeln, die als LOW eingestuft sind, vollständig, funktioniert nur in kauf-version
        # skip_check: LOW 

        # this should check only MEDIUM and higher
        check: MEDIUM
          
        # Die Pipeline bricht NUR bei MEDIUM, HIGH oder CRITICAL ab. 
        # LOW-Fehler werden ignoriert und führen nicht zu einem Pipeline-Stopp.
        ### hard_fail_on: CRITICAL
